### PR TITLE
Update GH actions

### PR DESCRIPTION
**Pull request by joanhey**
Fix, update and faster GH actions.

It's ready to be merged. Are compiling all php versions (except 8.2).

Still fail some tests, but are not from this PR. And PHP 8.2 that we know it ( @rryqszq4 check https://github.com/rryqszq4/ngx-php/pull/151/commits/4a16fd54ba6c5c0dcc8291ad1acdb37cc617cfb8)

And it's failing to compile with Nginx v1.12 (very old version). I delete it from the test, if you want you can add it again.

Later we will fix the tests.

Now will be easier and faster to fix  & update Ngx-php.

~PD: I think that TEST_DIR is not necessary. Deleted~

### CODE REVIEW

**Comment by joanhey** [comment]
@rryqszq4 here I need your help !!
https://github.com/rryqszq4/ngx-php/actions/runs/4569695602/jobs/8066222514?pr=151#step:5:641

**Comment by joanhey** [comment]
@rryqszq4 I need your help, with this PR
https://github.com/rryqszq4/ngx-php/actions/runs/4577682790/jobs/8083379497?pr=151#step:6:538

And you can check it here working in a dockerfile:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/php-ngx/php-ngx-mysql.dockerfile

Why is it marking the warnings as errors?
Could you help me to fix it ?

**Comment by rryqszq4** [comment]
> @rryqszq4 here I need your help !! https://github.com/rryqszq4/ngx-php/actions/runs/4569695602/jobs/8066222514?pr=151#step:5:641
> 
> I compile without problems in a clean docker, but not here in GH actions.
> 
> Update: Only show with PHP 8.2

Maybe compiler is old, 'if' judgment has been removed from php.

**Comment by joanhey** [comment]
The socket test use the url: https://hq.sinajs.cn/
But return always a `403 Forbidden`

**Pull request merged**
