### PR TITLE
Fix php 8 major version

### PR DESCRIPTION
**Pull request by joanhey**
image

Also fix dynamic modules test.
This PR is for the master branch.

### CODE REVIEW

**Comment by joanhey** [comment]
This need another ngx-php version !!

**Comment by rryqszq4** [comment]
> This need another ngx-php version !!

A new version https://github.com/rryqszq4/ngx-php/releases/tag/v0.0.29

**Comment by joanhey** [comment]
Change the version 
https://github.com/rryqszq4/ngx-php/blob/2eb62418bb6f73885ea824fb90a07cbd7a083a41/src/ngx_http_php_version.h#L32

**Comment by rryqszq4** [comment]
> Change the version
> 
> https://github.com/rryqszq4/ngx-php/blob/2eb62418bb6f73885ea824fb90a07cbd7a083a41/src/ngx_http_php_version.h#L32

Has been changed and re-tag https://github.com/rryqszq4/ngx-php/releases/tag/v0.0.29

**Comment by joanhey** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/actions/runs/7958592193/job/21723784900?pr=8739#step:9:803

Working OK.

**Pull request merged**
